#server:
#  port: 8081

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.cloud.config.client: DEBUG


#  datasource:
#    url: jdbc:postgresql://localhost:5432/fitness_user_db
#    username: postgres
#    password: admin123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#
#logging:
#  level:
#    reactor.netty.http.client: DEBUG
#    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
